# Generated by Django 4.2 on 2023-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='post_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=150),
        ),
    ]
