# Generated by Django 4.2 on 2023-05-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_is_delete_blogs_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='blog.blogs'),
        ),
    ]
